# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          command: build
          arguments: -t segment-kafka-consumer-relay

      - task: ECRPushImage@1
        displayName: 'Push image to segment ECR'
        inputs:
          awsCredentials: 'Segment ECR'
          regionName: 'eu-central-1'
          sourceImageName: 'segment-kafka-consumer-relay'        
          sourceImageTag: 'latest'
          repositoryName: 'segment'
          pushTag: '$(Build.BuildNumber)'
                  
      # Replace token values in yaml files with pipeline variables
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Replace tokens in yaml files'
        inputs:
          rootDirectory: '$(Build.SourcesDirectory)/k8s/'
          targetFiles: '*.yaml'
          tokenPrefix: '$('
          tokenSuffix: ')'

      # Apply Kubernetes manifests
      - task: Kubernetes@1
        displayName: 'Apply manifests'
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: 'Kubernetes-Hellman-Segment-Deploy'
          namespace: 'segment-ui-beorp'
          command: apply
          arguments: '-f $(Build.SourcesDirectory)/k8s/'