# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: '-t segment-kafka-consumer-relay:$(Build.BuildId)'
    - task: ECRPushImage@1
      displayName: 'Push backend image to Shared ECR'
      inputs:
        awsCredentials: 'Shared-Prod ECR-Push'
        regionName: 'eu-central-1'
        sourceImageName: 'segment-kafka-consumer-relay'        
        sourceImageTag: '$(Build.BuildNumber)'
        repositoryName: '825548240362.dkr.ecr.eu-central-1.amazonaws.com/segment'
        pushTag: '$(Build.BuildId)'
                
    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact: k8s manifests"
      inputs:
        PathtoPublish: k8s
        ArtifactName: manifests
