# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: '-t segment-kafka-consumer-relay:$(tag)'

    - task: ECRPushImage@1
      displayName: 'Push backend image to Shared ECR'
      inputs:
        awsCredentials: 'Shared-Prod ECR-Push'
        regionName: 'eu-central-1'
        imageSource: 'imagename'
        sourceImageName: 'segment-kafka-consumer-relay'
        repositoryName: 'dfds/segment-kafka-consumer-relay'
        pushTag: '$(Build.BuildId)'
                
    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact: k8s manifests"
      inputs:
        PathtoPublish: k8s
        ArtifactName: manifests
