apiVersion: apps/v1
kind: Deployment
metadata:
  name: segment-ui-beorp-kafka-consume-relay-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: segment-kafka-consumer-relay
        image: 825548240362.dkr.ecr.eu-central-1.amazonaws.com/segment/segment-kafka-consumer-relay:$(Build.BuildNumber)