apiVersion: apps/v1
kind: Deployment
metadata:
  name: segment-ui-beorp-kafka-consume-relay-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: segment-kafka-consumer-relay
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/segment-ui-beorp/segment-kafka-consumer-relay:$(Build.BuildId)